// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-QqbTjMyYj-4sWrOLjf-rhx1ueEMqNA',
    appId: '1:628203833973:web:ca6bdefd86322fe4a6063c',
    messagingSenderId: '628203833973',
    projectId: 'pawrent-c325b',
    authDomain: 'pawrent-c325b.firebaseapp.com',
    databaseURL: 'https://pawrent-c325b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pawrent-c325b.appspot.com',
    measurementId: 'G-RDE2RS9G69',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJBPffSdH5G1BF8AA7YAx-ePLOBzCR9w',
    appId: '1:628203833973:ios:e9c13a1b0568f22aa6063c',
    messagingSenderId: '628203833973',
    projectId: 'pawrent-c325b',
    databaseURL: 'https://pawrent-c325b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pawrent-c325b.appspot.com',
    iosClientId: '628203833973-3n5bl4jkm0dce5bl70ug3lqbpn8h6aem.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVJBPffSdH5G1BF8AA7YAx-ePLOBzCR9w',
    appId: '1:628203833973:ios:e9c13a1b0568f22aa6063c',
    messagingSenderId: '628203833973',
    projectId: 'pawrent-c325b',
    databaseURL: 'https://pawrent-c325b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pawrent-c325b.appspot.com',
    iosClientId: '628203833973-3n5bl4jkm0dce5bl70ug3lqbpn8h6aem.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeb',
  );
}
